apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
  namespace: model-serving
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}" 
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: OTEL_EXPORTER_JAEGER_AGENT_HOST
            value: "jaeger-jaeger.face-detection.svc.cluster.local"
          - name: OTEL_EXPORTER_JAEGER_AGENT_PORT
            value: "6831"
          ports:
            - containerPort: 8000