apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-jaeger
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: jaeger
  ports:
    - name: agent-compact
      port: 6831
      protocol: UDP
      targetPort: 6831
    - name: query
      port: 16686
      protocol: TCP
      targetPort: 16686
  type: ClusterIP  