## https://artifacthub.io/packages/helm/jaegertracing/jaeger
namespace: model-serving
provisionDataStore:
  cassandra: false
allInOne:
  enabled: false
storage:
  type: memory
agent:
  enabled: true
collector:
  enabled: true
query:
  enabled: true
